name: Acquire activation file

on:
  workflow_dispatch:

jobs:
  request-activation-file:
    name: Request manual activation file 🔑
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate activation file
        uses: game-ci/unity-request-manual-activation-file@v4
        with:
          unityVersion: 2020.3.11f1 # Cambia por la versión de Unity que estés usando
          activationFilePath: ./Unity_v2020.x.ulf

      - name: Upload activation file
        uses: actions/upload-artifact@v3
        with:
          name: Unity activation file
          path: ./Unity_v2020.x.alf
